Update cloudy.py
flaresimulations/synthesizer pull request #366
Opened 2023-10-31 14:16 UTC by stephenmwilkins

Turned off print statement in read_linelist function.

## Issue Type

- Bug
- Document
- Enhancement

## Checklist

- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-10-31 14:42 UTC, christopherlovell requested changes
Could you add a verbose flag argument to the method, turn it off by default, and then print this if enabled?

2023-11-01 13:18 UTC, stephenmwilkins commented
> Could you add a verbose flag argument to the method, turn it off by default, and then print this if enabled?

I really don't think it's essential, I think it was only there during some bug searching.

2023-11-01 13:59 UTC, christopherlovell approved these changes

2023-11-01 14:00 UTC, merged

2023-11-01 14:00 UTC, christopherlovell commented
I'd say delete the line rather than commenting it out then, but will merge now