Photoionisation improvements
flaresimulations/synthesizer pull request #369
Opened 2023-11-01 14:38 UTC by stephenmwilkins

Making photoionisation modelling more general (i.e. for different cloudy versions and possible other photoionisation codes).

- created `photoionisation/`
- moved current `cloudy.py` to this folder and renamed `cloudy17.py`
- moved generic functions to `photoionisation.py`
- some other tidying

2023-11-08 10:36 UTC, WillJRoper requested changes

2023-11-08 10:36 UTC, WillJRoper commented on synthesizer/photoionisation/__init__.py
> +from .photoionisation import *
Why are you importing everything and then importing cloudy17 explicitly below? We should avoid * imports in favour of clarity.

2023-11-08 10:36 UTC, WillJRoper commented on synthesizer/photoionisation/__init__.py
> +from .photoionisation import *
Also we shouldn't be using relative imports

2023-11-09 07:28 UTC, stephenmwilkins commented
With the change in structure I somehow managed to destroy this branch so closing it down and starting again.

2023-11-09 07:28 UTC, closed without merging