Implement apertures
flaresimulations/synthesizer pull request #537
Opened 2024-03-04 22:16 UTC by christopherlovell

Adds aperture masks to spectra generation methods in particle stars object. Does this by including centre of potential as an attribute on a particle galaxy object, which is then passed down to child stars objects, and used to calculate the distance when generating a mask on particles.

Also updates test data and generation scripts to include this property.

Still to do:
- implement apertures on gas particle distributions

## Issue Type
- Enhancement

## Checklist
- [x] I have read the [CONTRIBUTING.md]() -->
- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-03-07 16:48 UTC, WillJRoper requested changes
Looks good, some minor comments. Could we also implement a COM calculation if COP is not passed? I think I prefer writing a method on `Particles` for the COM and making the user call it explicitly after thinking for a moment on it. That way it's intentional. Then if the user calls anything that expects a centre and it's not been passed as a COP or calculated we error.

2024-03-12 14:44 UTC, christopherlovell commented on src/synthesizer/particle/stars.py
> +        centre_of_potential=None,
It is used in `_aperture_mask`. 

Unfortunately I can't find a way of making parent objects aware of their child classes. This is why it exists on both. It's a similar situation for redshift, which also has to be initialised on both.

2024-03-12 16:22 UTC, christopherlovell commented on src/synthesizer/particle/stars.py
> +        centre_of_potential=None,
updated initialisation on parent and passed on stars init

2024-03-12 20:42 UTC, WillJRoper approved these changes

2024-03-12 20:42 UTC, merged