Introducing velocity shifts in particle spectra (Will's modified version)
flaresimulations/synthesizer pull request #804
Opened 2024-12-19 18:56 UTC by WillJRoper

TODO...

## Issue Type

- Enhancement

## Checklist
- [ ] I have read the [CONTRIBUTING.md]() -->
- [ ] I have added docstrings to all methods
- [ ] I have added sufficient comments to all lines
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no pep8 errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-12-19 19:06 UTC, WillJRoper commented
@marcoleonardi97 I've had a play today. In doing so I split off into a different branch because I didn't want to edit your work but instead make the modifications separately so you can compare. 

There wasn't actually much at all holding it back from compiling. A few syntax errors but once those were fixed it was clear sailing to compile. 

Here I have:
- Done some small housekeeping. 
- Split off the mapping of shifted indices. This is done so we don't do it for each grid cell in the CIC versions. If we did it for every grid cell we'd repeat the same calculation `2^ndim` times. A big subtlety.
- The grid wavelengths needed passing so those have now been passed through to the C. 
- Swapped your `find_nearest_bin` for a binary search which will be faster. In big O notation, your loop version was at worst `O(N)` if the element you're looking for is at the end. The binary search is `O(log(n)` so much more efficient. (the binary search returns the upper bin so that required some minor modifications too).
- I added an example just to prove it works. 

By all means, move to using this branch or use it as a template, I don't mind. We can probably simplify the code a little by combining stuff together. I'm sure there's some time to be saved, so feel free to look at the performance.  

I need to fix some unrelated stuff that is now failing because of these modifications (mostly missing arguments in the integrated spectra stuff). Don't worry about that! 

Here's some plots showing your code working:

<img width="1045" alt="SCR-20241219-qlwn" src="https://github.com/user-attachments/assets/96fa9faf-f03b-4e97-9f69-670cfffc0643" />

Zoomed right in on a line

<img width="1048" alt="SCR-20241219-qlcd" src="https://github.com/user-attachments/assets/9ae4c554-ba07-43a8-aa2a-80eab85c3cc8" />

2025-01-07 17:50 UTC, WillJRoper commented
Thanks for all the hard work @marcoleonardi97. I've now got this all sorted and passing. It'll now be reviewed by another member of the team before being merged into the main branch.

2025-01-07 18:04 UTC, marcoleonardi97 commented
@WillJRoper thanks for cleaning it up for me ! can't wait to get some actual results

2025-01-15 08:25 UTC, christopherlovell commented
For the record, I think this should be a flag on an emission model, but happy to get this in for now

2025-01-15 08:38 UTC, christopherlovell requested changes

2025-01-15 08:38 UTC, christopherlovell commented on src/synthesizer/extensions/particle_spectra.c
> +int find_nearest_bin(double lambda, double *grid_wavelengths, int nlam) {
Not essential, but this could be named better

2025-01-15 08:38 UTC, christopherlovell commented on src/synthesizer/extensions/particle_spectra.c
> + * This is the serial version of the function.
should be the parallel version?

2025-01-15 08:38 UTC, christopherlovell commented on src/synthesizer/extensions/particle_spectra.c
> +  if (!PyArg_ParseTuple(args, "OOOOOOOOiiisiO", &np_grid_spectra, &np_lam,
What is this line doing?

2025-01-15 08:38 UTC, christopherlovell commented on examples/particle/plot_velocity_broadened_spectra.py
> +This example shows how to compute line of sight dust surface densities,
Incorrect doctrsing

2025-01-15 12:06 UTC, WillJRoper commented on src/synthesizer/extensions/particle_spectra.c
> +  if (!PyArg_ParseTuple(args, "OOOOOOOOiiisiO", &np_grid_spectra, &np_lam,
This is how you read Python arguments into C, the string tells it what sort of Python object to expect and then every other argument is the variable to populate.

2025-01-15 12:13 UTC, WillJRoper commented on src/synthesizer/extensions/particle_spectra.c
> +int find_nearest_bin(double lambda, double *grid_wavelengths, int nlam) {
Done

2025-01-15 12:13 UTC, WillJRoper commented on src/synthesizer/extensions/particle_spectra.c
> + * This is the serial version of the function.
Done

2025-01-15 12:13 UTC, WillJRoper commented on examples/particle/plot_velocity_broadened_spectra.py
> +This example shows how to compute line of sight dust surface densities,
Done

2025-01-15 12:14 UTC, WillJRoper commented
Agreed on the emission model having a flag. That's easy enough to do (and then the argument currently being used becomes an override like the others). I can do that separately very easily.

2025-01-15 15:40 UTC, christopherlovell approved these changes

2025-01-15 15:40 UTC, merged